config/routes.rb
Ohanasignupvtwo::Application.routes.draw do
  devise_for :admins
  root "categories#index"
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/slots/new', controller: 'slots', action: 'new', as: 'new_slot'
  post '/slots', controller: 'slots', action: 'create', as: 'slots'

  get '/slots', controller: 'slots', action: 'index'
  get '/slots/:id', controller: 'slots', action: 'show', as: 'slot'

  get '/slots/:id/edit', controller: 'slots', action: 'edit', as: 'edit_slot'
  patch '/slots/:id', controller: 'slots', action: 'update'

  delete '/slots/:id', controller: 'slots', action: 'destroy'

  get '/courses/new', controller: 'courses', action: 'new', as: 'new_course'
  post '/courses', controller: 'courses', action: 'create', as: 'courses'

  get '/courses', controller: 'courses', action: 'index'
  get '/courses/:id', controller: 'courses', action: 'show', as: 'course'

  get '/courses/:id/edit', controller: 'courses', action: 'edit', as: 'edit_course'
  patch '/courses/:id', controller: 'courses', action: 'update'

  delete '/courses/:id', controller: 'courses', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :slots
  has_one :slot

  has_many :courses, :through => :slots

  def full_name
    return "#{first_name} #{last_name}"
  end

  validates :first_name, :presence => true

  validates :last_name, :presence => true

  validates :email, :presence => true

  validates :phone, :presence => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.street_address = params[:street_address]
    @user.city = params[:city]
    @user.state = params[:state]
    @user.zip = params[:zip]
    @user.due_date = params[:due_date]
    @user.birth_place = params[:birth_place]
    @user.doc_midwife = params[:doc_midwife]
    @user.baby_gender = params[:baby_gender]
    @user.password_digest = params[:password_digest]

    if @user.save
      redirect_to categories_url, notice: "Thank you! Your registration has been completed successfully!"
    else
      render 'new'
    end

    course = Course.find_by(:id => params[:course_id])
    course.slots.each do |slot|
      if slot.available?
      slot.user_id = @user.id
      slot.available = false
      slot.save
      break
      end
    end

  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.street_address = params[:street_address]
    @user.city = params[:city]
    @user.state = params[:state]
    @user.zip = params[:zip]
    @user.due_date = params[:due_date]
    @user.birth_place = params[:birth_place]
    @user.doc_midwife = params[:doc_midwife]
    @user.baby_gender = params[:baby_gender]
    @user.password_digest = params[:password_digest]

    @user.slots.each do |slot|
      slot.available = true
      slot.user_id = nil
      slot.save
      end

      c = Course.find(params[:course_id])
      c.slots.each do |slot|
        if slot.available?
          slot.user_id = @user.id
          slot.available = false
          slot.save
          break
        end
      end

    if @user.save
      redirect_to users_url, notice: "User updated successfully."
    else
      render 'edit'
    end

   end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy

    redirect_to users_url, notice: "User deleted."
  end
end

app/views/users/edit.html.erb
<%= @user.slots %>

<div class="page-header">
  <h1>Editing User #<%= @user.id %></h1>
</div>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(user_url(@user), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :course_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%# if params[:course_id].present? %>
        <%#= select_tag :course_id, options_from_collection_for_select(Course.all.order(:start_date), :id, :full_course_title, Course.find_by(params[:course_id]), class: 'form-control') %>
      <%# else %>
        <%= select_tag :course_id, options_from_collection_for_select(Course.all.order(:start_date), :id, :full_course_title, @user.slot.course_id), class: 'form-control' %>
      <%# end %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, @user.first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, @user.last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, @user.email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :phone, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :phone, @user.phone, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :street_address, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :street_address, @user.street_address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :city, @user.city, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :state, @user.state, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :zip, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :zip, @user.zip, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :due_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :due_date, @user.due_date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :birth_place, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :birth_place, @user.birth_place, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :doc_midwife, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :doc_midwife, @user.doc_midwife, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :baby_gender, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :baby_gender, @user.baby_gender, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update User", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<p><%= link_to 'Add a New User', new_user_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Courses</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Due date</th>
      <th>Birth place</th>
      <th>Doc midwife</th>
      <th>Baby gender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.order(:last_name).each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <% user.courses.all.each do |course|%>
        <td><%= course.full_course_title %></td>
        <% end %>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.street_address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip %></td>
        <td><%= user.due_date %></td>
        <td><%= user.birth_place %></td>
        <td><%= user.doc_midwife %></td>
        <td><%= user.baby_gender %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, user_url(user), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_url(user), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(users_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :course_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%# if params[:course_id].present? %>
        <%#= select_tag :course_id, options_from_collection_for_select(Course.all.order(:start_date), :id, :full_course_title), Course.find_by(params[:course_id]), class: 'form-control' %>
      <%# else %>
        <%= select_tag :course_id, options_from_collection_for_select(Course.all.order(:start_date), :id, :full_course_title, params[:course_id]), class: 'form-control' %>

      <%# end %>
    </div>
  </div>


  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :phone, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :phone, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :street_address, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :street_address, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :city, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :state, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :zip, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :zip, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :due_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :due_date, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :birth_place, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :birth_place, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :doc_midwife, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :doc_midwife, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :baby_gender, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :baby_gender, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Sign Up!", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User #<%= @user.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>First name</dt>
  <dd><%= @user.first_name %></dd>

  <dt>Last name</dt>
  <dd><%= @user.last_name %></dd>

  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <dt>Phone</dt>
  <dd><%= @user.phone %></dd>

  <dt>Street address</dt>
  <dd><%= @user.street_address %></dd>

  <dt>City</dt>
  <dd><%= @user.city %></dd>

  <dt>State</dt>
  <dd><%= @user.state %></dd>

  <dt>Zip</dt>
  <dd><%= @user.zip %></dd>

  <dt>Due date</dt>
  <dd><%= @user.due_date %></dd>

  <dt>Birth place</dt>
  <dd><%= @user.birth_place %></dd>

  <dt>Doc midwife</dt>
  <dd><%= @user.doc_midwife %></dd>

  <dt>Baby gender</dt>
  <dd><%= @user.baby_gender %></dd>

   <dt>Course</dt>
   <% @user.courses.all.each do |course|%>
   <dd><%= course.full_course_title %></dd>
   <% end %>
</dl>