config/routes.rb
Ohanasignupvtwo::Application.routes.draw do
  devise_for :admins
  root "categories#index"
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/slots/new', controller: 'slots', action: 'new', as: 'new_slot'
  post '/slots', controller: 'slots', action: 'create', as: 'slots'

  get '/slots', controller: 'slots', action: 'index'
  get '/slots/:id', controller: 'slots', action: 'show', as: 'slot'

  get '/slots/:id/edit', controller: 'slots', action: 'edit', as: 'edit_slot'
  patch '/slots/:id', controller: 'slots', action: 'update'

  delete '/slots/:id', controller: 'slots', action: 'destroy'

  get '/courses/new', controller: 'courses', action: 'new', as: 'new_course'
  post '/courses', controller: 'courses', action: 'create', as: 'courses'

  get '/courses', controller: 'courses', action: 'index'
  get '/courses/:id', controller: 'courses', action: 'show', as: 'course'

  get '/courses/:id/edit', controller: 'courses', action: 'edit', as: 'edit_course'
  patch '/courses/:id', controller: 'courses', action: 'update'

  delete '/courses/:id', controller: 'courses', action: 'destroy'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by(id: params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new
    @course.start_date = params[:start_date]
    @course.end_date = params[:end_date]
    @course.category_id = params[:category_id]
    @course.cost = params[:cost]
    @course.place = params[:place]
    @course.start_time = params[:start_time]
    @course.end_time = params[:end_time]
    @course.teacher = params[:teacher]

    if @course.save
      redirect_to courses_url, notice: "Course created successfully."
    else
      render 'new'
    end

    8.times do
      @slot = Slot.new
      @slot.course_id = @course.id
      @slot.available = true
      @slot.save
    end
  end

  def edit
    @course = Course.find_by(id: params[:id])
  end

  def update
    @course = Course.find_by(id: params[:id])
    @course.start_date = params[:start_date]
    @course.end_date = params[:end_date]
    @course.category_id = params[:category_id]
    @course.cost = params[:cost]
    @course.place = params[:place]
    @course.start_time = params[:start_time]
    @course.end_time = params[:end_time]
    @course.teacher = params[:teacher]

    if @course.save
      redirect_to courses_url, notice: "Course updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find_by(id: params[:id])
    @course.destroy

    redirect_to courses_url, notice: "Course deleted."
  end
end

app/views/courses/edit.html.erb
<div class="page-header">
  <h1>Editing Course #<%= @course.id %></h1>
</div>

<% if @course.errors.any? %>
  <% @course.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(course_url(@course), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :start_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :start_date, @course.start_date.strftime("%b %e, %Y"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :end_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :end_date, @course.end_date.strftime("%b %e, %Y"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cost, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cost, @course.cost, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :place, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :place, @course.place, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :start_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :start_time, @course.start_time.strftime("%l:%M%p"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :end_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :end_time, @course.end_time.strftime("%l:%M%p"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :teacher, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :teacher, @course.teacher, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Course", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/courses/index.html.erb
<div class="page-header">
  <h1>Courses</h1>
</div>

<p><%= link_to 'Add a New Course', new_course_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>State date</th>
      <th>End date</th>
      <th>Category</th>
      <th>Cost</th>
      <th>Place</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Teacher</th>
      <th>Available Slots</th>
      <th>Booked Slots</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.order(:start_date).each do |course| %>
      <tr>
        <td><%= course.start_date.strftime("%b %e, %Y") %></td>
        <td><%= course.end_date.strftime("%b %e, %Y") %></td>
        <td><%= course.category.name %></td>
        <td><%= course.cost %></td>
        <td><%= course.place %></td>
        <td><%= course.start_time.strftime("%l:%M%p") %></td>
        <td><%= course.end_time.strftime("%l:%M%p") %></td>
        <td><%= course.teacher %></td>
        <td><%= course.slots.where(:available => true).count %></td>
        <td><%= course.slots.where(:available => false).count %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, course_url(course), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_course_url(course), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, course_url(course), method: 'delete', data: { confirm: "Do you really want to delete this course?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<div class="page-header">
  <h1>New Course</h1>
</div>

<% if @course.errors.any? %>
  <% @course.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(courses_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :start_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
    <%= text_field_tag :start_date, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :end_date, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :end_date, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cost, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cost, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :place, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :place, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :start_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :start_time, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :end_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :end_time, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :teacher, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :teacher, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Course", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/courses/show.html.erb
<div class="page-header">
  <h1>Course #<%= @course.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>State date</dt>
  <dd><%= @course.start_date.strftime("%b %e, %Y") %></dd>

  <dt>End date</dt>
  <dd><%= @course.end_date.strftime("%b %e, %Y") %></dd>

  <dt>Category</dt>
  <dd><%= @course.category.name %></dd>

  <dt>Cost</dt>
  <dd><%= @course.cost %></dd>

  <dt>Place</dt>
  <dd><%= @course.place %></dd>

  <dt>Start time</dt>
  <dd><%= @course.start_time.strftime("%l:%M%p") %></dd>

  <dt>End time</dt>
  <dd><%= @course.end_time.strftime("%l:%M%p") %></dd>

  <dt>Teacher</dt>
  <dd><%= @course.teacher %></dd>

  <dt>Available Slots</dt>
  <dd><%= @course.slots.where(:available => true).count %></dd>

  <dt>Users Signed Up</dt>
  <% @course.users.all.each do |user|%>
  <dd><%= user.full_name %></dd>
  <% end %>

</dl>