config/routes.rb
Ohanasignupvtwo::Application.routes.draw do
  devise_for :admins
  root "categories#index"
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/slots/new', controller: 'slots', action: 'new', as: 'new_slot'
  post '/slots', controller: 'slots', action: 'create', as: 'slots'

  get '/slots', controller: 'slots', action: 'index'
  get '/slots/:id', controller: 'slots', action: 'show', as: 'slot'

  get '/slots/:id/edit', controller: 'slots', action: 'edit', as: 'edit_slot'
  patch '/slots/:id', controller: 'slots', action: 'update'

  delete '/slots/:id', controller: 'slots', action: 'destroy'

  get '/courses/new', controller: 'courses', action: 'new', as: 'new_course'
  post '/courses', controller: 'courses', action: 'create', as: 'courses'

  get '/courses', controller: 'courses', action: 'index'
  get '/courses/:id', controller: 'courses', action: 'show', as: 'course'

  get '/courses/:id/edit', controller: 'courses', action: 'edit', as: 'edit_course'
  patch '/courses/:id', controller: 'courses', action: 'update'

  delete '/courses/:id', controller: 'courses', action: 'destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :courses

  validates :name, :presence => true

  validates :description, :presence => true

  validates :image, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new
    @category.name = params[:name]
    @category.description = params[:description]
    @category.image = params[:image]

    if @category.save
      redirect_to categories_url, notice: "Category created successfully."
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    @category.name = params[:name]
    @category.description = params[:description]
    @category.image = params[:image]

    if @category.save
      redirect_to categories_url, notice: "Category updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy

    redirect_to categories_url, notice: "Category deleted."
  end
end

app/views/categories/edit.html.erb
<div class="page-header">
  <h1>Editing Category #<%= @category.id %></h1>
</div>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(category_url(@category), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, @category.name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :description, @category.description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image, @category.image, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Category", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="container">

  <div class="innerbody">

    <div class="jumbotron innerbody">
      <h1>Classes & Groups</h1>
      <div>
        <br>
      </div>
      <% if admin_signed_in?%>
      <p><%= link_to 'Add a New Category', new_category_url, class: 'btn btn-primary' %></p>
      <% end %>
    </div>

    <% @categories.each do |category| %>
      <div class="course">
        <div class="row">
          <div>
            <img class="col-md-5" class="list_photo" src="<%= category.image %>">
          </div>
          <div class="description">
            <h2><%= category.name.capitalize %></h2>
            <p><%= category.description %></p>
          </div>
          <%= form_tag(new_user_url, :method => 'get') do %>
            <div>
              <h3 class="pink">Available Dates</h3>
              <p><%= select_tag :course_id, options_from_collection_for_select(category.courses, :id, :course_date_time)%>
            </div>

            <div>
              <%= button_tag "Enroll Now", class: 'btn_orange btn-lg' %>
            </div>
          <% end %>

          <% if admin_signed_in? %>
            <span><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_category_url(category), class: 'btn btn-warning' %></span>
            <span><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, category_url(category), method: 'delete', data: { confirm: "Do you really want to delete this category?" }, class: 'btn btn-danger' %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="page-header">
  <h1>New Category</h1>
</div>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(categories_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :description, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Category", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="page-header">
  <h1>Category #<%= @category.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Image</dt>
  <dd><%= @category.image %></dd>

  <dt>Name</dt>
  <dd><%= @category.name %></dd>

  <dt>Description</dt>
  <dd><%= @category.description %></dd>

</dl>